# Generated by Django 3.1.1 on 2021-05-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210419_0641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
